# Some of the documentation in this file was generated by AI

# Stage 1: Base image with dependencies
FROM python:3.12-slim AS builder
RUN echo "Building the base image with dependencies"

WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Copy and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir --target=/tmp/deps -r requirements.txt

# Stage 2: Final image
FROM python:3.12-slim AS final
RUN echo "Creating the final image"

WORKDIR /app

# Copy installed dependencies and source code
COPY --from=builder /tmp/deps /app/deps
COPY . /app/

# Set PYTHONPATH so Python can find copied dependencies
ENV PYTHONPATH="/app/deps"

# Expose default Flask port
EXPOSE 5000

# Run the Flask app
ENTRYPOINT ["python"]
CMD ["app.py"]